name: bump

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '*/20 * * * *'
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt-get update && sudo apt-get install -y curl git jq bash

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        echo "$(date '+%w')" | md5sum > hash
        git add hash
        nohup bash -c "git commit -m 'chore' && git push" >/dev/null 2>&1 &


    - name: Bump
      run: |
        printf '%s' "${{ secrets.config }}" | base64 -d | sudo bash
